### ISSUE TITLE
Добавить документацию

### ISSUE THREAD

**Issue by artbear** [nixel2007/gitrunner#1]
- [ ] Описание тестирования через 1bdd
- [ ] Упомянуть, что запускать фичи `1bdd ./features` нужно из корня

**Comment by nixel2007** [comment]
Я бы переименовал задачу в "Добавить документацию" :D

Это в планах.

**Comment by artbear** [comment]
Легким движением руки :)

**Comment by nixel2007** [comment]
Какая никакая - готова
