### ISSUE TITLE
Клонирование последнего коммита

### ISSUE THREAD

**Issue by artbear** [nixel2007/gitrunner#17]
`git clone --depth=1 <remote_repo_url>`

Было бы здорово получить этот функционал.
Он очень пригодится в тестах/фичах

Например, у меня в ванесса-раннер нужно протестировать прогон тестов через xUnitFor1C и Vanessa-behavior.
Как сабмодули их подключать не хочется, т.к. эти модули нужны для только тестирования.

В тесте я бы клонировал нужную ветку с ограничением объема клонирования и использовал.

очень хочется заюзать гитраннер в тестах для исключения работы с командами гитами как консольными командами.

**Comment by nixel2007** [comment]
Реализовано в 1.2.0
