### ISSUE TITLE
в программный интерфейс добавить НайтиСсылкиНаЗадачи

### ISSUE THREAD

**Issue by ghost** [nixel2007/gitrunner#36]
Нужно как-то найти коммиты привязанные к задачам через # учитывая что могут быть ключевые слова fix bи т.д.

Например в целях когда нужно дернуть СППР или еще чего-то когда он является основной системой учета задач

**Comment by nixel2007** [comment]
Думаю, что не только через решетку. 
Что конкретно ты хочешь получить? Это две разные подзадачи - отдельно поиск коммитов, привязанных к задаче (по определённому шаблону), отдельно поддержка ключевых слов. Но зачем она в гитраннере? Это логика прикладного ПО.

**Comment by allustin** [comment]
@nixel2007 хочу упростить написание прикладного ПО как раз... возможно ты прав задача в другую библиотеку и возможно связана с библиотекой regexp.

суть в том что такое прикладное ПО у нас попросили написать ;-)

P.S. Иди на море - хватит мониторить github

**Comment by nixel2007** [comment]
Там ещё рядом лежит соседняя задачка про получение истории в виде ТЗ. Это точно полезно и должно помочь в прикладной задаче.
