### ISSUE TITLE
Gitrunner logo proposal

### ISSUE THREAD

**Issue by reallinfo** [nixel2007/gitrunner#42]
Hello, I am a graphic designer. I contribute to open source softwares by designing logos. Do you want me to design a logo for Gitrunner?. I will wait for feedback. Have a nice day!

**Comment by nixel2007** [comment]
@reallinfo hello! sure, i'll glad to see your work!

**Comment by reallinfo** [comment]
Sure, Here is my logo and  idea.

![gitrunner](https://user-images.githubusercontent.com/36298335/40740694-2a26995c-6452-11e8-92df-7e09b8a4ebac.jpg)

**Comment by khorevaa** [comment]
@nixel2007 I like upper! Good idea!

**Comment by khorevaa** [comment]
@reallinfo Pls logo for https://github.com/khorevaa/orca may be same from eve-online -)

**Comment by reallinfo** [comment]
I don't quite understand what you mean. 

If you like the logo, I can send a pr.

**Comment by nixel2007** [comment]
@reallinfo it's really cool! Could you send a PR with the red one?

**Comment by nixel2007** [comment]
Also it would be really nice if you make a logo for https://github.com/EvilBeaver/OneScript 
OneScript is a free implementation of interpreter for russian proramming language 1C:Enterprise. It is very popular for CI-CD tasks in "1C world"

**Comment by reallinfo** [comment]
I sent a pr. Please check it https://github.com/nixel2007/gitrunner/pull/43

Sure, I will try to design a logo for OneScript.
