### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by git22ura** [nixel2007/gitrunner#46]
Коллеги, подскажите можно ли использовать гитраннер в случае получения/пуша из непубличных (т.е. закрытых и требующих авторизации) репозиториев?
Спасибо

**Comment by nixel2007** [comment]
Можно в автоматическом режиме (без запрашивания ввода логина/пароля):
* через ssh-ключ
* через указание логина/пароля в uri репозитория
* через GIT_ASKPASS

в общем любой вариант, не требующий ввода из stdin

**Comment by git22ura** [comment]
А я правильно понимаю, что в случае ssh-ключа не должен быть установлен пароль на его использование?

**Comment by nixel2007** [comment]
может быть установлен и пароль, если настроить запуск ssh-агента. но по самим ssh-агентам лучше спросить коллег в гиттере, я нечасто пользуюсь ссх-ключами для гита и пока еще не задолбался вводить пароль :)

**Comment by git22ura** [comment]
Спасибо, Никита.
