### ISSUE TITLE
Ошибка при получении вывода команды, не нужный СокрЛП()

### ISSUE THREAD

**Issue by 240596448** [nixel2007/gitrunner#53]
Вывод статуса. В первой строке первый пробел - значащий (состояние в индексе)
![image](https://user-images.githubusercontent.com/35220983/145481025-7d727eca-42de-497b-8ccd-7c02805ed869.png)
Проблема в [здесь (строка 865)](https://github.com/nixel2007/gitrunner/blob/f2270678a52ac1c2214b9649c401440cf3363a8f/src/%D0%93%D0%B8%D1%82%D0%A0%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9.os#L865)

Вопрос: где потенциально может вылезти проблема, если отказаться от СокрЛП() ?

**Comment by nixel2007** [comment]
Насколько я помню, были проблемы с пробелами _справа_. с пробелами слева может и не будет проблем. что скажут тесты?

**Comment by 240596448** [comment]
> Насколько я помню, были проблемы с пробелами _справа_. с пробелами слева может и не будет проблем. что скажут тесты?

Фича-тесты проходят... За исключением одного #54

**Comment by 240596448** [comment]
... и получения Субмодулей (упал, исправлено)
+ обработка лишних пустых строк в получении списка веток
+ обработка лишних пустых строк в команде списка настроект git config --list (явно упадет, если будет пустая строка)
(все исправлено там же в PR)

**Comment by nixel2007** [comment]
Закрываем?
